### ISSUE TITLE
Engangskode sparebank 1

### ISSUE THREAD

**Issue by SpikedCoffee** [akc3n/banking#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Engangskode sparebank 1

### Link to app

https://play.google.com/store/search?q=engangskode+sparebank+1&c=apps

### App version

v3.0.6

### Country of the app

Norway

### Build Number

SQ3A.220605.009.B1.2022063000

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything works.

**Comment by okpersonvern** [comment]
This app still works completely fine. Tested on app version 2024.01.12. Pixel 6a build UQ1A.240105.002.2024011600

**Comment by tockudex** [comment]
> Could someone please confirm that it still works?

Works for the most part.

But whenever I close my work profile for a while and then reopen the app, I have to set it up from the ground up (BankID, setting up a password, etc.)...

Did someone experience the same thing and fix it?

**Comment by leierx** [comment]
I've experienced the same thing. You have to go through the full setup process again after a day or so... Very annoying and not normal behavior.

Issue is present on both my Pixel 9 Pro, and my Pixel 10 Pro.

**Comment by leierx** [comment]
I created a support ticket with them mentioning this issue, and I suggest y'all do the same :D

**Comment by tockudex** [comment]
> I created a support ticket with them mentioning this issue

Already reached out to them, but without real success. I should try again though!
What did you mention in your ticket? I mean what details did you provide?

**Comment by leierx** [comment]
@tockudex Just mentioned this issue, and reported the error I've got on my pixel 9 and 10.

Got the following  answer:
> GrapheneOS is not a Google Play-certified operating system. Even though it is security-focused, Play Integrity / Attestation will therefore classify it as unapproved. This means that certain security mechanisms in the app will not be available. This is a limitation controlled by Google's security checks and is not something we can override from the app side.

**Comment by tockudex** [comment]
Gosh, thanks for the follow-up...

If only we could convince banking app devs to drop the play integrity in favour of the hardware attestation -_-

Did you actually mention it in your ticket, the hardware attestation?

**Comment by spring-onion** [comment]
> But whenever I close my work profile for a while and then reopen the app, I have to set it up from the ground up (BankID, setting up a password, etc.)...

> I've experienced the same thing. You have to go through the full setup process again after a day or so... Very annoying and not normal behavior.

Can you check if this is reproducible in a normal secondary profile and especially the owner one?

> GrapheneOS is not a Google Play-certified operating system. Even though it is security-focused, Play Integrity / Attestation will therefore classify it as unapproved. This means that certain security mechanisms in the app will not be available. This is a limitation controlled by Google's security checks and is not something we can override from the app side.

They can use the [hardware attestation api](https://grapheneos.org/articles/attestation-compatibility-guide) alongside play integrity and let you pass if either of these two checks succeed. They don't need to disband play integrity for compatibility reasons if they insist on using it.

**Comment by tockudex** [comment]
>Can you check if this is reproducible in a normal secondary profile and especially the owner one?

Until now, I didn't want to set up the play gogle on my main profile, but I might give it a shot.

>They can use the [hardware attestation api](https://grapheneos.org/articles/attestation-compatibility-guide) alongside play integrity and let you pass if either of these two checks succeed.

Absolutely, but before reaching out to them about that possibility, I'll wait to see if something happens on that front (a maintained list for those hardware keys, but from potentially multiple custom ROM's, as proposed by p1gp1g in [#287](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/issues/287#issuecomment-4089016181)).

**Comment by tockudex** [comment]
>Can you check if this is reproducible in a normal secondary profile and especially the owner one?

Setting up the app on the main profile without the default hardening settings worked just fine even without play store services.

However, the app still resets after a while.
