### ISSUE TITLE
Up Money [Australia]

### ISSUE THREAD

**Issue by wale** [akc3n/banking#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Up

### Link to app

https://play.google.com/store/apps/details?id=au.com.up.money&hl=en

### App version

v2.2.19

### Country of the app

Australia

### Build Number

SQ3A.220605.009.B1.2022062200

### Device

- [X] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [X] Enforced
- [ ] Not enforced
- [ ] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

SafetyNet is checked based on a React Native library ([jailmonkey](https://github.com/GantMan/jail-monkey)), though it only shows a popup that detects if your device is rooted. Once clicking off of it, the app can be used as normal.

### Are there any extra notes you think users should know about?

This was tested in mid-June, I no longer have Graphene installed on the device.

**Comment by blaxpot** [comment]
This report mislead me a bit - I just installed the Up Money app from the Aurora store in my Main user profile (without Google Play) on a Pixel 7a, and everything so far seems to be working OK.

Granted, I obviously can't add my card to Google Pay, but I was given the option to order a physical card (which I guess I will stick in a pouch on the back of my phone case), so the app can still be useful.

**Comment by blaxpot** [comment]
I suppose the report doesn't explicitly say that the above won't work - it just kind of gave me that impression.

But for anyone reading this in future - give it a try!
