### ISSUE TITLE
ABN AMRO

### ISSUE THREAD

**Issue by AltF02** [akc3n/banking#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

ABN AMRO

### Link to app

https://play.google.com/store/apps/details?id=com.abnamro.nl.mobile.payments

### App version

12.11

### Country of the app

the Netherlands

### Build Number

SQ3A.220705.003.A1.2022072000

### Device

- [x] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [x] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Works perfect, so far all features I've tested work. Just like stock OS

**Comment by aerique** [comment]
Also works on Pixel 6 Pro without Google Play and Google Play Services installed.
