### ISSUE TITLE
[temp] Due to unforeseen circumstances regarding @akc3n, app reports will not be reviewed for now

### ISSUE THREAD

**Issue by Zanthed** [akc3n/banking#109]
Due to unforeseen circumstances regarding @akc3n, app reports will not be reviewed for now.

Feel free to continue to report them, but they will not be reviewed until further notice.

**Comment by akc3n** [comment]
I'm back now and will be continuing with the app report reviews. Thank you to everyone who kept on submitting back app reports, and to @Zanthed for posting the pinned notice letting everyone know about the situation.
