### ISSUE TITLE
Avanza - Sweden

### ISSUE THREAD

**Issue by erlaan** [akc3n/banking#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Avanza

### Link to app

https://play.google.com/store/apps/details?id=se.avanzabank.androidapplikation

### App version

v5.3.0

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [ ] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

App work. You can check your stocks and trade stocks

### Are there any extra notes you think users should know about?

This is app is for the Swedish market.

**Comment by akc3n** [comment]
Thanks @erlaan
