### ISSUE TITLE
Pixel 6a X Belfius (Belgian bank)

### ISSUE THREAD

**Issue by ozls** [akc3n/banking#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Belfius Mobile

### Link to app

https://play.google.com/store/apps/details?id=be.belfius.directmobile.android

### App version

22.2.0 (221671620)

### Country of the app

Belgium

### Build Number

SD2A.220601.004.2022080300

### Device

- [x] Pixel 6a
- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

It seems to do absolutely everything (fingerprint, sending money, mobile payments...) except sending notifications on banking events (incoming money, low amount...)

### Are there any extra notes you think users should know about?

This was observed with the Pixel 6a (not among device choices at the moment; I have added it in my issue)

**Comment by 1991martijn-max** [comment]
Can confirm it works on Pixel 9a
I do have play services installed, no tinkering or anything needed. install app, login and go

**Comment by antrodec** [comment]
Not working anymore. Got an errror telling the app was installed from another store (I installed it from Google qplay)

**Comment by ozls** [comment]
> Not working anymore. Got an errror telling the app was installed from another store (I installed it from Google qplay)

I'm not having this issue

**Comment by antrodec** [comment]
Did you install it from Play Store ? Do you use any alternate app store ?

**Comment by ozls** [comment]
I use Aurora Store, but it's the same thing. It gets apps from the Play Store with a spoofed account.

**Comment by trgr-boi** [comment]
Not working for me. On my owners profile I get the message "there are apps installed that are not  installed via the official app store" and on a separate banking profile with only playstore, password manager and belfius app, I get "not working on rooted or modified operating system".

I am on a Pixel 6a and is version 2026091900.
