### ISSUE TITLE
ADCB Bank UAE - Working

### ISSUE THREAD

**Issue by ellias-dev** [akc3n/banking#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

ADCB

### Link to app

https://play.google.com/store/apps/details?id=com.adcb.bank

### App version

10.2

### Country of the app

United Arab Emirates

### Build Number

SQ3A.220705.004.2022081800

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [X] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [X] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Used on Pixel4 and Pixel6, GrapheneOS from the stable channel. At the time (a year ago) it did work without any Google stuff installed on Pixel4, but can't vouch for now.
The app is fully functional.

**Comment by humaidq** [comment]
I can confirm still working, although the application now requires phone permission.
