### ISSUE TITLE
Privat24 (Privatbank app) - works

### ISSUE THREAD

**Issue by ellias-dev** [akc3n/banking#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Privat24

### Link to app

https://play.google.com/store/apps/details?id=ua.privatbank.ap24

### App version

6.47.00

### Country of the app

Ukraine

### Build Number

SQ3A.220705.004.2022081800

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [X] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [X] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Used on Pixel4 and Pixel6, GrapheneOS from the stable channel. The app keeps asking for SMS permission for Google Play Services, but SMSs come without giving this permission. Other than that, the app is fully functional.

**Comment by nazar-pc** [comment]
Application launches and works fine, but it is not able to provide contact-less payments feature on its own and requires Google Pay for that, which doesn't work.

Verified on GrapheneOS (Android 13) on Google Pixel 7 Pro, application version 6.54.00.

It did ask for various permissions for Google Play, I just suppressed that notification.
