### ISSUE TITLE
First Direct (UK) App

### ISSUE THREAD

**Issue by bootlesshacker** [akc3n/banking#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

First Direct

### Link to app

https://play.google.com/store/apps/details?id=com.firstdirect.bankingonthego&gl=UK

### App version

4.15.0

### Country of the app

United Kingdom

### Build Number

TP1A.220624.021.2022082400

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

No observed issues. App just seems to work with all features normally available

### Are there any extra notes you think users should know about?

No

### ADB logcat of the app if necessary

N/A

**Comment by codingmayhem** [comment]
App still works July 2024. This is with their new secure key feature that rolled out recently. Only issue on signup is that the text verification code only comes after you click send again. It doesn't seem to send it automatically from the setup wizzard, so you need to manually trigger it to send by clicking I've not received a code --> Send Again

**Comment by eylenburg** [comment]
I updated the app today and get "service unavailable" now when I open it. Does anyone else have similar problems? I'm concerned the app update might have broken something.
