### ISSUE TITLE
PhonePe UPI App

### ISSUE THREAD

**Issue by takeda-discord** [akc3n/banking#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

PhonePe

### Link to app

https://play.google.com/store/apps/details?id=com.phonepe.app

### App version

v4.1.39.220817

### Country of the app

India

### Build Number

TP1A.220624.014.2022082400

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [X] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

PhonePe is a UPI payment app used in India. The app opens as expected and I was able to register my device without any issues. I was also able to successfully send money using the app.

**Comment by akc3n** [comment]
Thank you @takeda-discord

**Comment by Inventhrice** [comment]
I have not encountered issues so far with the Google Pixel 8a.

App version: v25.02.12.0
Device: Pixel 8a
Google Play: Installed
Google Play Network permission revoked? No
SafetyNet Enforcement: Unsure
Native code debugging: Allowed
Stock OS compatibility: Untested
Profile app tested in:  Main user profile

Description of the app's functionality:
I was able to log in into the application with no problems. I only was able to test it on a surface level (like logging in, checking if the camera would work to scan QR codes, and looking at account settings), and I haven't encountered any issues nor errors yet. When I get the chance to live with the application, I may update this.

**Comment by Inventhrice** [comment]
Hi! So full disclosure, Im not a full time user of the application, so I have no day to day experience with it. Having said that, I did a quick look at the offered functionality and it seemed to be working still?

**Comment by spring-onion** [comment]
@Inventhrice Affected user can't go beyond the verification step when they link their bank. Please share your settings.

**Comment by Inventhrice** [comment]
Is there any specific setting you'd like me to report back on? I too have been struggling with the verification step, but that is also because my bank account has had some weirdness with it, so it's not the fault of the OS. The problems I was initially facing seem to have resolved itself after not looking into it for months now, so unfortunately I couldn't tell you much on that either sorry!

**Comment by hegdenischay** [comment]
Hi, happy to help on this issue. I currently use this app pretty often, and it works flawlessly.

**Comment by spring-onion** [comment]
User granted google play the nearby devices permission, enabled compatibility mode and connected via cellular data instead of wifi, it works for them now. Appreciate the help everyone!
