### ISSUE TITLE
Axis Bank (UTI Bank)

### ISSUE THREAD

**Issue by empratyush** [akc3n/banking#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Axis Mobile - Pay,Invest & UPI

### Link to app

https://play.google.com/store/apps/details?id=com.axis.mobile

### App version

v7.8

### Country of the app

India

### Build Number

TP1A.220624.021.A1.2022083000

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [X] Pixel 4a
- [ ] Pixel 4 XL
- [X] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

everything seems to work including paying via Qr code/UPI (with or without google play)

**Comment by PVTejas** [comment]
I believe this needs to be updated, as the Axis Bank app now requires play services to be enabled.

Edit: Tested on Pixel 8a
