### ISSUE TITLE
Bank Austria

### ISSUE THREAD

**Issue by besamim** [akc3n/banking#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Bank Austria MobileBanking

### App version

v8.3.2

### Country of the app

Austria

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [x] Pixel 4a
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [x] Installed
- [ ] Not installed

### Google Play Network permission revoked?

- [x] Revoked
- [ ] Not revoked
- [ ] I did not have Google Play installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [x] Unsure

### Native code debugging

- [ ] Enabled
- [x] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [x] Not tested

### Profile app tested in

- [ ] Main user profile
- [x] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

App works without any issues (fingerprint login, payments, authentication). Notifications won't work if the network permission for Google services is revoked.

**Comment by JC2k8** [comment]
Same result here, same phone. Tested with v8.4.0 though, using my main profile with Google Play network permission *not* removed.

Here's the missing link: https://play.google.com/store/apps/details?id=com.bankaustria.android.olb

Everything worked. Activating MobileTAN (push notification) worked (switched from SMS-TAN), including scanning the holographic label on the back of the bano card.

**Comment by akc3n** [comment]
> Same result here, same phone. Tested with v8.4.0 though, using my main profile with Google Play network permission _not_ removed.
> 
> Here's the missing link: https://play.google.com/store/apps/details?id=com.bankaustria.android.olb
> 
> Everything worked. Activating MobileTAN (push notification) worked (switched from SMS-TAN), including scanning the holographic label on the back of the bank card.

Thanks very much for the missing link and feed back!
