### ISSUE TITLE
Tangerine Bank - Canada

### ISSUE THREAD

**Issue by Peter-Easton** [akc3n/banking#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Tangerine Mobile App

### Link to app

https://play.google.com/store/apps/details?id=ca.tangerine.clients.banking.app

### App version

v4.11.0

### Country of the app

Canada

### Device

- [X] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play Network permission revoked?

- [X] Revoked
- [X] Not revoked
- [ ] I did not have Google Play installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Completely functional, no issues noted.

Only tested with Play Services. Not tested without.

### Are there any extra notes you think users should know about?

Also tested on Pixel 4 with November 2021 release.

**Comment by akc3n** [comment]
Thanks @Peter-Easton

**Comment by Inventhrice** [comment]
This also works for the Google Pixel 8a.

App version: v4.48.1
Device: Pixel 8a
Google Play: Installed
Google Play Network permission revoked? No
SafetyNet Enforcement: Unsure
Native code debugging: Allowed
Stock OS compatibility: Untested
Profile app tested in:  Main user profile

Description of the app's functionality:
Completely functional, no issues noted.
