### ISSUE TITLE
Simplii Financial - Canada

### ISSUE THREAD

**Issue by Peter-Easton** [akc3n/banking#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Simplii Financial

### Link to app

https://play.google.com/store/apps/details?id=com.pcfinancial.mobile

### App version

v7.29.6

### Country of the app

Canada

### Device

- [X] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play Network permission revoked?

- [X] Revoked
- [X] Not revoked
- [ ] I did not have Google Play installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Completely functional with or without Google Play Services having network permission.

### Are there any extra notes you think users should know about?

Tested on Pixel 4 (November 2021 release) and found to be working.

**Comment by akc3n** [comment]
Thank you very much @Peter-Easton

**Comment by bgilhome-now** [comment]
Working for SMS OTC verification, but not via push notifications (Get "This device can't be registered ... (6086)" within the app -> Settings & Security -> Use push notifications

**Comment by 4fosaefp** [comment]
> Working for SMS OTC verification, but not via push notifications (Get "This device can't be registered ... (6086)" within the app -> Settings & Security -> Use push notifications

I'm able to register the device after installing sandboxed Google Play service.

**Comment by antarctic3431** [comment]
> Working for SMS OTC verification, but not via push notifications (Get "This device can't be registered ... (6086)" within the app -> Settings & Security -> Use push notifications

I am also unable to register for push notification-based OTP-2FA within the app, though all other functions work as expected. When attempting to register for **push verification codes** I get an error message stating that the device cannot be registered, with error code 6086 (same as @bgilhome-now). This is on version 7.59.2 of the app.

@4fosaefp I've tried enabling Phone and Sensors permissions for Google Play Services, though the error persists.
