### ISSUE TITLE
Tomorrow Mobile Banking - Germany

### ISSUE THREAD

**Issue by togethereveryday** [akc3n/banking#20]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### App name
*What is the banking app called?*

**Tomorrow Mobile Banking*

### Link to app

**[https://play.google.com/store/apps/details?id=one.tomorrow.app&hl=en_US&gl=US](https://play.google.com/store/apps/details?id=one.tomorrow.app&hl=en_US&gl=US)**

### App version

**2.76.0**

### Country of the app

**Germany*

### Device
*Which Pixel(s) have you tested this with?*

- [ ] Pixel 6 Pro
- [x] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [x] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [x] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [x] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [x] Not enforced
- [ ] Unsure

### Native code debugging

- [x] Enabled
- [ ] Disabled

### Stock OS compatibility

- [x] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [x] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality  

**Everything works as expected.**

*Example:* 
- [x] Login / Registration
- [x] Verification Code
    - [x] SMS  
    - [ ] E-mail
    - [ ] Phone 
- [x] Biometrics
- [x] Deposit a Cheque
- [x] Alerts

### Are there any extra notes you think users should know about?

**No**

**Comment by StrangeGirlMurph** [comment]
Still works in September 2025 with the app version 3.103.1 on Pixel 4a
