### ISSUE TITLE
Penta - Germany

### ISSUE THREAD

**Issue by togethereveryday** [akc3n/banking#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Penta - Business Banking App

### Link to app

https://play.google.com/store/apps/details?id=com.getpenta.app&hl=en_US&gl=US

### App version

2.2.2

### Country of the app

Germany

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [X] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [X] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything is functional.

**Comment by akc3n** [comment]
Thank you @togethereveryday for you list of submitted banking apps from Germany. Very much appreciated!

**Comment by togethereveryday** [comment]
Glad to help.

------- Original Message -------
