### ISSUE TITLE
CTBC Bank - Taiwan

### ISSUE THREAD

**Issue by IchikaZou** [akc3n/banking#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

中國信託行動銀行 Home Bank

### Link to app

https://play.google.com/store/apps/details?id=com.chinatrust.mobilebank

### App version

5.0.39

### Country of the app

Taiwan

### Device

- [X] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Online banking and other functions work fine.

**Comment by akc3n** [comment]
Thank you @IchikaZou
