### ISSUE TITLE
Airbank - Czech Republic

### ISSUE THREAD

**Issue by shibattor** [akc3n/banking#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

My Air

### Link to app

https://play.google.com/store/apps/details?id=cz.airbank.android

### App version

7.1.0

### Country of the app

Czech Republic

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [X] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything (payments, 2FA verification etc.) works fine. I haven't tried paying with NFC, but it requires Google Pay.

**Comment by akc3n** [comment]
Hey thanks for your help @shibattor
