### ISSUE TITLE
HSBC

### ISSUE THREAD

**Issue by hjangadi** [akc3n/banking#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

HSBC

### Link to app

Play Store

### App version

3.17.0

### Country of the app

United Kingdom

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Hi All,

This works absolutely fine on Pixel 6 running with Sandbox google services with GrapheneOS; happy to use grapheneOS until I get support. No going back to Pixel stock. 

As my NFC payment system also resolved with Stocard app. I recommend this.

### Are there any extra notes you think users should know about?

As my NFC payment system also resolved with Stocard app as Gpay didnt work on my GrapheneOS althought I have installed Sanbox Google services. I recommend this.

### ADB logcat of the app if necessary

no, not required.

**Comment by akc3n** [comment]
@hjangadi thank you very much! Is this the correct information below?
---

## App Name
HSBC UK Mobile Banking

## Link to App
https://play.google.com/store/apps/details?id=uk.co.hsbc.hsbcukmobilebanking&hl=en

- [ ] Verify with @hjangadi  that this missing information to full App name and Link to App is the correct one

**Comment by hjangadi** [comment]
yes correct. Sorry I should have had copied the link. Next time I would definitely mention this. I am new to GrapheneOS/Github

**Comment by akc3n** [comment]
Thanks again @hjangadi really appreciate it

**Comment by eylenburg** [comment]
3.61.0 still works for me. Pixel 8, installed in Private Space with Play Services and Secure App Spawning disabled (because of another app).

**Comment by eylenburg** [comment]
>It was Shizuku. It seems it was turning on USB & wireless debugging on device restart. Disabled Shizuku and I can now access HSBC again.

Can confirm. I tried the same. Developer mode on is not a problem, but USB/Wireless debugging on breaks the HSBC app. And Shizuku seems to turn it on in the background.

**Comment by eylenburg** [comment]
Since the newest update (v3.74.0) I now get "security issue detected. we detected apps on your device that pose a potential security risk (...) to restore access, please uninstall any virtual space apps". I have it running in a work profile (set up with Shelter) and installed from Aurora. App compatibility mode is enabled because otherwise it crashes with a hardened malloc error (also not a problem in the previous version). I installed it in the private space but it's also not working with the same error ("virtual space apps"). In the main profile it works apparently but only after switching to the default keyboard app before opening HSBC.
