### ISSUE TITLE
Volksbanken Raiffeisenbanken - Companion App

### ISSUE THREAD

**Issue by nani8ot** [akc3n/banking#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Pay - Deine Bezahl App

### Link to app

https://play.google.com/store/apps/details?id=de.fiduciagad.android.vrwallet

### App version

v21.15.0

### Country of the app

Germany

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [X] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [X] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything I tested worked

Works:
- add bank cards of the bank account (tested with girocard)
- contactless payment works

Works in main profile:
- set "Pay" as default payment provider

### Are there any extra notes you think users should know about?

The work profile device manager app used was Shelter from F-Droid.

**Comment by akc3n** [comment]
@nani8ot 
Hey thanks very much for your submitted report. I will add it to the site when I get back from work this evening.

**Comment by Letgamer** [comment]
Hey there, maybe someone can help me out here, VR Banking and VR Secure Go Plus are working for me, but I can't get the Pay app to work. When trying to add a card the app always states: "At the moment you cannot purchase a card. Please check your Internet connection or contact your bank"

**Comment by robovoice1** [comment]
https://www.kuketz-blog.de/nfc-datenschutzfreundlich-bezahlen-mit-dem-android-phone/

**Comment by Letgamer** [comment]
Yes, I were, but as it was 1 year ago I unfortunately don't remember how.
But I can state for the record, that the Pay App, the SecureGo App and the VR Banking App are still working without problems in Android 15👍

**Comment by vbrandl** [comment]
I just had to grant network permissions to Google Play Services. Now it works. Thank you.
