### ISSUE TITLE
Amex UK

### ISSUE THREAD

**Issue by shompoe** [akc3n/banking#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Amex United Kingdom

### Link to app

https://play.google.com/store/apps/details?id=com.americanexpress.android.acctsvcs.uk

### App version

6.51.1

### Country of the app

United Kingdom

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [X] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [X] Enforced
- [ ] Not enforced
- [ ] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything works except the mobile wallet feature which checks for ctsProfile.

Without Google play services the app cannot be installed.

**Comment by akc3n** [comment]
@shompoe thank for your time and contribution.

**Comment by JohnKonsolakis** [comment]
I am encountering an issue with loging into the Amex UK app on a Pixel 6a with sandboxed Google Play services. The app just returns the prompt 'your password is incorrect' (even when it is correct) or enters the loading screen without moving further.

**Comment by edent** [comment]
App works, but it won't remember the device for Two-Step Verification.

When I toggle the "Remember This Device" switch, it says:

> We were unable to remember your device at this time. Please try again later.

Pixel 8 Pro. Remembering works on stock firmware, but not on latest Graphene OS.

**Comment by jamesh1999** [comment]
I am also encountering the issue where the app won't remember my device for Two-Step Verification. Unfortunately, the app does not give an informative error message.

Pixel 7a. I have tested the compatibility mode / allowing native code debugging but these do not help.

**Comment by dniku** [comment]
I observed the same issue with remembering device on stock Samsung S22 Ultra firmware with the app installed through Aurora Store instead of Google Play Store. Switching the installation method to Play Store fixed it. 

Curious if the issue is reproducible on GOS with Play Store installation.

**Comment by edent** [comment]
@dniku I use the Play Store version on GOS and it has this problem.

**Comment by quagsirus** [comment]
I'm having the same "remember device" issue on the official Android QPR2 beta on my Pixel 10, so this might not be a GrapheneOS specific problem

**Comment by FreddieDev** [comment]
Seeing the same, Pixel 9A on GrapheneOs

**Comment by quagsirus** [comment]
Just wanted to add that in my experience, when the "remember device" security checks fail, a flag gets added at an account (not device) level, and is automatically cleared after (what seems to be) 1 month. So if you try changing things to see if it fixes the issue, you won't know for quite a while. Found out since one of the official betas on my Pixel failed SafetyNet for 1 day, and I had to wait a month before I could login without an OTP again, on any of my devices, even though the problem with the beta was fixed long before.

**Comment by knirirr** [comment]
I've also had the problem of inability to remember the device on a Pixel 10, GrapheneOS.
Additionally, Amex have introduced a virtual card feature during the last year. This appears to try loading a web page, which times out.
I reported both issues to them.
