### ISSUE TITLE
Fifth third bank 

### ISSUE THREAD

**Issue by meramsey** [akc3n/banking#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Fifth Third Mobile Banking

### Link to app

https://play.google.com/store/apps/details?id=com.clairmail.fth

### App version

v3.60

### Country of the app

United States

### Device

- [X] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

It works as expected.
Just wanted to report it for listing been using this for a few months now without issues

### Are there any extra notes you think users should know about?

NA

### ADB logcat of the app if necessary

na

**Comment by akc3n** [comment]
@meramsey hey, there! Appreciate your help with the report.

**Comment by MMachado05** [comment]
Hey there! Playing with the idea of getting Graphene. Has it still been working for you some years later?

**Comment by meramsey** [comment]
> Hey there! Playing with the idea of getting Graphene. Has it still been working for you some years later?

yep still works for me use daily

**Comment by feroxi-s** [comment]
Having issues with app version 5.17.1 on Pixel 6a. Play installed, network permission not revoked, native code debugging enabled, working fine on stock Android 16. The login button just shows the loading indicator when I enter my credentials and press it. No improvement after granting the optional location access it requested.

**Comment by feroxi-s** [comment]
Tried again today and read access is working (I don't do transfers or deposits with 5/3). Trying to turn on biometric login fails with a nonspecific error but that's not critical.
