### ISSUE TITLE
german Sparkasse app 

### ISSUE THREAD

**Issue by robovoice1** [akc3n/banking#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Sparkasse

### Link to app

https://play.google.com/store/apps/details?id=com.starfinanz.smob.android.sfinanzstatus

### App version

6.02

### Country of the app

Germany

### Device

- [X] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Checking your account balance
Realtime/normal payments 
Standing orders
Enable Giropay/Kwitt
Enable Mobile Payment
Enable/Disable money transfers to IBANs from foreign countries
Find the nearest ATM
Monthly banking statements to download (pdf)

### Are there any extra notes you think users should know about?

You need a second (tan) app on the same smartphone for realtime or normal payments.
It is called "S-pushTAN".
https://play.google.com/store/apps/details?id=com.starfinanz.mobile.android.pushtan

**Comment by robovoice1** [comment]
Also worth to mention:
Do not switch to Google Play Store beta within GOS updater app.  The bank app freezes on start!

**Comment by akc3n** [comment]
> Also worth to mention: Do not switch to Google Play Store beta within GOS updater app. The bank app freezes on start!

Noted.
Thank you for the helpful information you shared. Much appreciated.

**Comment by PhysicsIsAwesome** [comment]
Also works on a secondary profile without Play Services. The only thing that didn't work was taking pictures of invoices, because it uses Play Services to access the camera.

> You need a second (tan) app on the same smartphone for realtime or normal payments.
It is called "S-pushTAN".

This depends on which Sparkasse and which TAN method has been selected. A lot of Sparkasse customers use chipTAN with an extra TAN generator device.

**Comment by robovoice1** [comment]
@PhysicsIsAwesome : on the first view the app is working, but you cannot download/view your monthly bank statements (pdf) within the mail account of the bank app.  If you try to access your mail account in the bank app the message no google play store installed appears.

Before you could also get  hardware tan generators, but they changed it (cheaper?)

**Comment by PhysicsIsAwesome** [comment]
> @PhysicsIsAwesome : on the first view the app is working, but you cannot download/view your monthly bank statements (pdf) within the mail account of the bank app. If you try to access your mail account in the bank app the message no google play store installed appears.

Works fine fine on my device. 

> Before you could also get hardware tan generators, but they changed it (cheaper?) 

This could also depend on the region. Not every region is the same. On my region it is still available.

**Comment by baermathias** [comment]
Mobile payment should be removed from the functionality, because for this you need a separate app, which does not work with GrapheneOS

**Comment by robovoice1** [comment]
updated this issue, thanks for reporting @baermathias

**Comment by robovoice1** [comment]
I also set everything to "alpha" channel (all apps in Apps app and GrapheneOS update channel with absolutely no problems. Forget my first comment (outdated/not true anymore) 😀

**Comment by robovoice1** [comment]
updated with detailed guide for nfc contactless payment with Android Stock and GrapheneOS:
https://www.kuketz-blog.de/nfc-datenschutzfreundlich-bezahlen-mit-dem-android-phone/

and hardware based ChipTAN

**Comment by Moyai88** [comment]
Can someone give me a update on this? The app worked on my old pixel, tried to set it up on my pixel 9 but get an error code "9001" that there's no TAN available. I also tried quick setup where i can use a phone where im already signed in to sign in on my other device. Somehow the device can't be found, even tho both have bluetooth enabled.

Play services obviously enabled on both.

**Comment by PhysicsIsAwesome** [comment]
> Can someone give me an update on this?

Both "Sparkasse" and "S-pushTAN" work fine on a Pixel 8 Pro with and without Play Services.

> I also tried quick setup where i can use a phone where im already signed in to sign in on my new device. Somehow the device can't be found, even tho both have bluetooth enabled.

Are you talking about "S-pushTAN" and its functionality to move from one device to another via Bluetooth? I also tried it. Didn't work for a week or two, then it suddenly did, without changing anything. If it does not work for you, you can go to a bank branch and register your new device there, or get a registration code sent via post mail.

**Comment by Moyai88** [comment]
> Both "Sparkasse" and "S-pushTAN" work fine on a Pixel 8 Pro with and without Play Services.
>
> > I also tried quick setup where i can use a phone where im already signed in to sign in on my new device. Somehow the device can't be found, even tho both have bluetooth enabled.
> 
> Are you talking about "S-pushTAN" and its functionality to move from one device to another via Bluetooth? I also tried it. Didn't work for a week or two, then it suddenly did, without changing anything. If it does not work for you, you can go to a bank branch and register your new device there, or get a registration code sent via post mail.

I'm talking about the s-Pushtan app, yes.
The Bluetooth option worked to quick-setup my pixel 7. via my IPhone. I tried to use both of my old phone's to login via Bluetooth, both didn't work. Device couldn't be found.

I also had my old QR code to register for the s-Pushtan app, it told me that there wasn't a TAN available as said.   After googling the error code, I found a forum post from a Xiaomi user that didn't have play services, that's why I thought they started using the play integrity API now.

I also can't sign in with the normal Sparkasse-App even tho I'm 100% sure I have the right login credentials. 
I will speak with them about the issue I guess..

**Comment by Moyai88** [comment]
> I'm talking about the s-Pushtan app, yes. The Bluetooth option worked to quick-setup my pixel 7. via my IPhone. I tried to use both of my old phone's to login via Bluetooth, both didn't work. Device couldn't be found.
> 
> I also had my old QR code to register for the s-Pushtan app, it told me that there wasn't a TAN available as said. After googling the error code, I found a forum post from a Xiaomi user that didn't have play services, that's why I thought they started using the play integrity API now.
> 
> I also can't sign in with the normal Sparkasse-App even tho I'm 100% sure I have the right login credentials. I will speak with them about the issue I guess..

The Issue has been fixed now. The "device couldn't be found" error was a known bug for like 2 months. 

It was fixed with the newest version of "s-Push-Tan".  They still don't use the play integrity api.

**Comment by Samuel-bot-web** [comment]
I have an issue where i am stuck in a loop while triing to send money. The app is requesting me over and over again to enter my online banking pin. Setting the app to remember the pin does not help. When starting the app it is also asking for the pin once.
I already tried to reinstall everything and the compatibilety mode but nothing helps. The push tan app is working fine.

**Comment by ostrocka** [comment]
> I have an issue where i am stuck in a loop while triing to send money. The app is requesting me over and over again to enter my online banking pin. Setting the app to remember the pin does not help. When starting the app it is also asking for the pin once. I already tried to reinstall everything and the compatibilety mode but nothing helps. The push tan app is working fine.

Same here, tried two different phones.
