### ISSUE TITLE
Banking app's compatibility in Belgium

### ISSUE THREAD

**Issue by Gosuser** [akc3n/banking#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

ING Belgium

### Link to app

https://play.google.com/store/apps/details?id=com.ing.banking

### App version

V4.4

### Country of the app

Belgium

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Bank application

### Are there any extra notes you think users should know about?

Installed GSF only and disabled all permissions

**Comment by akc3n** [comment]
@Gosuser thank you very much, this will be helpful to many people.

**Comment by waluwaz** [comment]
Works OK on Pixel 9 Pro XL with July 2025 version of the app. Owner user. No Google in that user. (But Play and GPS in secondary profile.)
