### ISSUE TITLE
ING Banking to go - Germany

### ISSUE THREAD

**Issue by zeritti** [akc3n/banking#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

ING Banking to go

### Link to app

https://play.google.com/store/apps/details?id=de.ingdiba.bankingapp&hl=de&gl=US

### App version

5.11.2 (585)

### Country of the app

Germany

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [X] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

I use the app mainly for the following tasks:
- Bank transfers
- Approval of online payments, e.g. via a credit card or PayDirect, Klarna
- Viewing stock market development charts
- Authentication when logging in to the bank's online portal

### Are there any extra notes you think users should know about?

The app works quite well for the afore-mentioned purposes without Goole Play Services on Pixel 3a XL (currently GrapheneOS SP2A.220305.012.2022032715) and has since GrapheneOS 11. I have not yet found a feature that does not work but assume that I have not used the whole of its functionality like setting a bank account or using notifications.

**Comment by besendorf** [comment]
Also works on Pixel 4a with and without Google Play and on Pixel 6 Pro with Google Play.
Only work with Native Code debugging in all cases for me

**Comment by akc3n** [comment]
Thanks for the update @besendorf 
Gosh, I'm sorry I totally missed this a long time ago. Apologies.
Updated the app report with your state changes.

**Comment by dmorady1** [comment]
Do notifications work @besendorf, since the main thread says that he doesn`t use notifications.
Would help a lot if you can comment about it if you use notifications.
Thank you.

**Comment by besendorf** [comment]
Notifications work Ehen enabled in the App and after granting the permission. I habe sandboxed GApps installed

**Comment by dmorady1** [comment]
Nice to hear. What do exactly mean by enabled in App? Do you mean that you give the app the permission for notifications?

Thank you very much and wish you a Happy New Year!

**Comment by besendorf** [comment]
The App has a toggle for notifications in its settings

**Comment by dmorady1** [comment]
Ah I see. Thank you very much and I wish you a Happy New Year!

**Comment by besendorf** [comment]
> On my Google Pixel Pro 7 I can't turn on notifications for ING Banking to go - Germany. It prompts an error if I try to do it:
> 
> ![signal-2023-04-28-202311_002](https://user-images.githubusercontent.com/18471911/235224567-74e4169b-f7df-49a4-b9a4-48392b418ff3.png)

Do you habe GApps installed?

**Comment by ProPatte** [comment]
> Do you habe GApps installed?

Yes. GrapheneOS makes it possible to install Google Play Store etc. in a sandbox: https://grapheneos.org/usage#sandboxed-google-play

![signal-2023-04-28-203937_002](https://user-images.githubusercontent.com/18471911/235227592-7316a9c4-e943-4c35-89e2-772cfb4f0adb.png)

**Comment by ProPatte** [comment]
I figured out that you need to be signed into the Google Play Store for it to work. It's not enough for it to only be installed! To do that you need to allow network permissions for the Play Store and the Google Framework when logging in the first time. After that you can turn off network permissions (at least for the Google Framework).

**Comment by robovoice1** [comment]
https://www.kuketz-blog.de/nfc-datenschutzfreundlich-bezahlen-mit-dem-android-phone/

**Comment by BreakfastSerial** [comment]
Does the ING Deutschland still work on GrapheneOS in 2025?

**Comment by besendorf** [comment]
yes

**Comment by RettetAale** [comment]
At this time I've some issues with the App on GrapheneOS, anybody else? The App don't accept any money transfer

**Comment by besendorf** [comment]
Never had any problems. Do you use Google Play?

**Comment by RettetAale** [comment]
Yes, this and another box always, who say, try at later is coming

![Image](https://github.com/user-attachments/assets/b01e52b5-3c39-429b-85e5-5ce8e2c844a5)

**Comment by mmhat** [comment]
I experience problems with the app:
After starting it the logo of the bank shows, but then it doesn't go any further.
It used to work like three weeks ago, and I am not sure whether it changed with an update of the app or because I installed the GsmCompat layer and Google Play Services.

Does anyone have similar problems?

EDIT: It's worth noting that I am still on Android 13 as Graphene OS's base version; I.e. my device is not officially supported anymore (Pixel 4).

**Comment by BreakfastSerial** [comment]
> I figured out that you need to be signed into the Google Playstore for it to work. It's not enough for it to only be installed! To do that you need to allow network permissions for the Playstore and the Google Framework when logging in the first time. After that you can turn off network permissions for the Google Framework.
> 
> Then you can turn on notifications in ING app as described before and there should be no error anymore.
> 
> Hope this helps someone in the future.

~~Does anyone else have had a similar experience? I can't get the notifications to work, I'm still facing the same error message as @ghost in their post.~~

~~I have Google Playstore and Services installed, am signed in and it has network permissions. I can't find any Google Framework to grant permissions to tough. On a Pixel 8 Pro.~~

I was able to activate notifications now, without changing anything in the app configuration or GOS itself. The only notable thing that changed, between my attempts, was the WiFi network I was connected to. Initially I had a Pi-Hole active on the network, while it worked on a network without Pi-Hole. Maybe that's a red herring. I'll see if I can pinpoint the issue.

EDIT: I repeated the complete process on a secondary device and faced the same error again. However, this time I was able to pinpoint the exact issue. My local Pi-Hole blocked two domains, that are addressed by the application during the activation of the notifications.

"firebaseinstallations.googleapis.com" and "in.appcenter.ms" need to be accessible for the app during the activation, I've received notifications without any issues, while blocking the domains on a DNS level, after the option has been activated in the app.

**Comment by KungFuCrafter** [comment]
I was using the [de.ingdiba.bankingapp](https://play.google.com/store/apps/details?id=de.ingdiba.bankingapp) on GrapheneOS (Pixel 8) for about a year without Google Play Services installed (only GmsCompatConfig and installed through Aurora Store). I was able to view my accounts and accept/decline transfers.

A couple of months ago this stopped working. On the main screen nothing is shown, and if I swipe down to load, it just loads indefinitely. 
Transactions are shown, but after "accepting" them, it just fails and says to repeat.

Is it now necessary to use GooglePlay Services? Does it work for any others without?

I also tried to activate compatibility mode on GOS, but this didn't help.

**Comment by BreakfastSerial** [comment]
> I was using the [de.ingdiba.bankingapp](https://play.google.com/store/apps/details?id=de.ingdiba.bankingapp) on GrapheneOS (Pixel 8) for about a year without Google Play Services installed (only GmsCompatConfig and installed through Aurora Store). I was able to view my accounts and accept/decline transfers.
> 
> A couple of months ago this stopped working. On the main screen nothing is shown, and if I swipe down to load, it just loads indefinitely. Transactions are shown, but after "accepting" them, it just fails and says to repeat.
> 
> Is it now necessary to use GooglePlay Services? Does it work for any others without?
> 
> I also tried to activate compatibility mode on GOS, but this didn't help.

I'm not sure - I have the Google Play Services installed via the Graphene App Store.
You could check with a secondary profile on GOS, with GooglePlay Services installed, to validate if it works there. If so, you could keep the app on that profile and allow notifications to be posted between profiles.

**Comment by KungFuCrafter** [comment]
> > I was using the [de.ingdiba.bankingapp](https://play.google.com/store/apps/details?id=de.ingdiba.bankingapp) on GrapheneOS (Pixel 8) for about a year without Google Play Services installed (only GmsCompatConfig and installed through Aurora Store). I was able to view my accounts and accept/decline transfers.
> > A couple of months ago this stopped working. On the main screen nothing is shown, and if I swipe down to load, it just loads indefinitely. Transactions are shown, but after "accepting" them, it just fails and says to repeat.
> > Is it now necessary to use GooglePlay Services? Does it work for any others without?
> > I also tried to activate compatibility mode on GOS, but this didn't help.
> 
> I'm not sure - I have the Google Play Services installed via the Graphene App Store. You could check with a secondary profile on GOS, with GooglePlay Services installed, to validate if it works there. If so, you could keep the app on that profile and allow notifications to be posted between profiles.

Nevermind, I just had to reinstall the app and resign in. It now works with and without GooglePlay Services.

**Comment by f1nch87** [comment]
Just switched to GOS.
Installed ING APP via Sandboxed Google Play and now i get this failure in both apps (old and New phone )![Screenshot_20260516-072021.png](https://github.com/user-attachments/assets/01c53528-0ca5-4e81-ae3d-d2ee8ba826f2)

**Comment by translate2765** [comment]
it's working for me but I had to disable memory tagging. also had to allow native code debugging and dynamic code loading via memory. 

Weirdly memory tagging didn't give me an error (i turned on notification for crashes). The app just closes after 1-2 seconds after opening when its on.

**Comment by translate2765** [comment]
@f1nch87 I got this error a couple of times too, had to change VPN to a different IP and that fixed it

**Comment by f1nch87** [comment]
It started to work. Dunno if a technical service member fixed something internally but it is working. Sometimes i get the fault but when igoe through the menues it disappears.
