### ISSUE TITLE
Danske Bank - Denmark

### ISSUE THREAD

**Issue by oumno** [akc3n/banking#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Mobilbank DK – Danske Bank

### Link to app

https://play.google.com/store/apps/details?id=com.danskebank.mobilebank3.dk

### App version

2022.1

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [x] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything in the app works. Transfer money, check account balanaces, messaging, settings, biometrics. 

### Are there any extra notes you think users should know about?

This is the Danish version of Danske Bank.

This app also works without Google Play. Please note, when logging in for the first time (before you enable biometrics) you need to sign in with NemID - which does not work without Google Play (you need to verify on separate device with Google Play to make this work).

**Comment by akc3n** [comment]
@oumno Thank you for taking the time to submit the app report.
