### ISSUE TITLE
Texans Credit Union

### ISSUE THREAD

**Issue by galt001** [akc3n/banking#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Texans CU mobile

### Link to app

https://play.google.com/store/apps/details?id=com.ifs.banking.fiid1373

### App version

2021.11.00

### Country of the app

United states

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [X] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Just a banking app.

### Are there any extra notes you think users should know about?

Works fine.

**Comment by akc3n** [comment]
Thanks @galt001
