### ISSUE TITLE
Monzo Bank (UK)

### ISSUE THREAD

**Issue by ojoeth** [akc3n/banking#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Monzo

### Link to app

https://play.google.com/store/apps/details?id=co.uk.getmondo

### App version

4.24.1

### Country of the app

United Kingdom

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything works with the exception of Google Pay, although that is a known unfixable OS issue and not anything to do with Graphene.

### Are there any extra notes you think users should know about?

Google Play Services is required for notifications to function correctly.

**Comment by akc3n** [comment]
Thank you @ojoeth

**Comment by Kat299** [comment]
Can confirm Monzo works even without Google Play Services installed, no error about root, etc. Of course notifications don't work without play services but other than that, no issues whatsoever

**Comment by FredHappyface** [comment]
Hi all,

I'm investigating migrating to grapheneos and wanted to understand what any support if any we'd have going forwards. 

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/d17347dd-db44-45a2-b262-d97d276e24e6" />
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/f476953e-e580-4dd0-916b-6e06f2a93851" />

In regards to using Monzo online, I got a fairly vague answer. Essentially you can in a pinch. But realistically not as you can with other providers 

<img width="985" height="1213" alt="Image" src="https://github.com/user-attachments/assets/6c7a0140-4dd7-4c14-828a-ff676add93ab" />


Hope this helps

**Comment by FredHappyface** [comment]
Just to confirm this works for me on main profile with GMS, compatibility mode for. Topping up a t212 card via true layer behaved as expected 

```
Version 7.27.0
versionCode 7270051
Installed: 21 May 2026; 19:31
```

**Comment by ShaunyRoo** [comment]
The website says that the app needs secure app spawing disabled, however that is not the case. It works just fine with it on.

**Comment by captainhook** [comment]
Correct; I've always used it without changing any system level settings, no issues whatsoever.
