### ISSUE TITLE
Flatex

### ISSUE THREAD

**Issue by PhysicsIsAwesome** [akc3n/banking#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

flatex next

### Link to app

https://play.google.com/store/apps/details?id=de.xcom.flatexde

### App version

2020.31

### Country of the app

Germany

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [X] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Basic app functionality works. Haven't tested any trading functionality.

### Are there any extra notes you think users should know about?

Most users need to also use the flateXsecure (https://play.google.com/store/apps/details?id=de.xcom.flatex.ptan) app for 2FA, which seems to work  (v 2020.6).

**Comment by akc3n** [comment]
Thank you @PhysicsIsAwesome
