### ISSUE TITLE
Swish payments - Sweden

### ISSUE THREAD

**Issue by oumno** [akc3n/banking#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Swish payments

### Link to app

https://play.google.com/store/apps/details?id=se.bankgirot.swish

### App version

5.4.2

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [x] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

You can sign-in, send money, receive money and see your history. You can enable biometrics and access settings.

### Are there any extra notes you think users should know about?

This app is a Swedish app.
It works without Google Play Services.

**Comment by akc3n** [comment]
@oumno Thanks again for your time and contribution to this banking apps project. Much appreciated!
