### ISSUE TITLE
Discover

### ISSUE THREAD

**Issue by Mr-Queso** [akc3n/banking#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Discover Mobile

### Link to app

https://play.google.com/store/apps/details?id=com.discoverfinancial.mobile

### App version

2204.0

### Country of the app

United States

### Build Number

SP2A.220405.003.2022040400

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [X] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything seems to work as expected. I did not test any notification functionality.

**Comment by dnerever** [comment]
**Link to app**

https://play.google.com/store/apps/details?id=com.discoverfinancial.mobile
**App version**

2403.0
**Country of the app**

United States
**Build Number**

2024022600

**Device**

- [x] Pixel 8

**Google Play installed**

- [ ] Installed
- [x] Not installed

**Google Play services Network permission revoked?**

    

- [x] Revoked
- [ ] Not revoked
- [ ] I did not have Google Play services installed

**SafetyNet Enforcement**

- [ ] Enforced
- [ ] Not enforced
- [x] Unsure

**Native code debugging**

    

- [ ] Enabled
- [x] Disabled

**Stock OS compatibility**

    

- [ ] Works
- [ ] Does not work
- [x] Not tested

**Profile app tested in**

    

- [x] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

**Description of the app's functionality**

Everything seems to work as expected. I did not test any notification functionality.
