### ISSUE TITLE
Grow Financial

### ISSUE THREAD

**Issue by sawft99** [akc3n/banking#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Grow Mobile Banking

### Link to app

https://play.google.com/store/apps/details?id=com.growfinancialfcu.growfinancialfcu&gl=US

### App version

3022.1.0.7598

### Country of the app

United States

### Build Number

SP2A.220405.003.2022040400

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [X] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Management of bank account. View balances, view account info, change account info, transfer money to other accounts, manage loans and make payments.

**Comment by akc3n** [comment]
Thanks @sawft99
