### ISSUE TITLE
Affinity Credit Union - Canada

### ISSUE THREAD

**Issue by xmy555a4apple** [akc3n/banking#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Affinity Mobile

### Link to app

https://play.google.com/store/apps/details?id=ca.affinitycu.mobile&hl=en

### App version

5.2.6

### Country of the app

Canada

### Build Number

SP2A.220405.003.2022041300

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [X] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

I can: pay bills, transfer money between accounts, send money, deposit (deposit of actual cash doesn't work :) ) 

### Are there any extra notes you think users should know about?

Installed through Aurora Store

**Comment by akc3n** [comment]
Thanks @xmy555a4apple I will get this added to the list this evening.
