### ISSUE TITLE
Credit Suisse

### ISSUE THREAD

**Issue by julianfairfax** [akc3n/banking#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Credit Suisse

### Link to app

https://play.google.com/store/apps/details?id=com.csg.cs.dnmb

### App version

8.0.0

### Country of the app

Switzerland

### Build Number

SP2A.220405.003.2022041300

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [X] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Works fine.

**Comment by akc3n** [comment]
@julianfairfax  thank you. I'll get this added when I'm home.

**Comment by akc3n** [comment]
Thanks again @julianfairfax, apologies for not being able to add this sooner, was tied up with holiday events this weekend.
