### ISSUE TITLE
Westpac - Australia (Submitting for non-gh user)

### ISSUE THREAD

**Issue by akc3n** [akc3n/banking#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Westpac

### Link to app

https://play.google.com/store/apps/details?id=org.westpac.bank

### App version

10.6.0

### Country of the app

Australia

### Build Number

SP2A.220405.003.2022041600

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [X] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [X] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [X] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

> "Westpac" works perfectly no matter what, with or without compatibility layer and any type of profile, however it does not have an inbuilt Tap and Pay feature and you have to use Google Pay, which i have not tested 

Quoted from DM message from user whom submitted this app report me via matrix.

### Are there any extra notes you think users should know about?

Quoted from DM message from user whom submitted this app report me via matrix.

**Comment by fryorcraken** [comment]
Now crashes on Pixel 7 with no google play

**Comment by rjo12** [comment]
Preliminary testing on a Pixel 8 (only in the main user profile).

Most functions (access of account information, personal information, etc) work flawlessly, with or without Google Play services installed.

Setting up the "push notification" functionality in the App (which gives notifications of transactions on accounts, etc) simply hangs without Google Play Services, or if Google Play services is installed in default configuration.     That functionality is set up and seems to work flawlessly on granting Google Play Services the Location permission (even if restricted to "Allow only while using the app").

Revoking network permission (for both Google Play Store and Google Play Services) doesn't seem to affect working of the App.

**Comment by rjo12** [comment]
Followup on my preceding comment.

Further testing has found that my previous observation about needing the Location permission was an error on my part.

I installed the Shelter app, installed Google Play via Apps into the Work profile, and then installed/cloned the Westpac App in the Work profile.  

It works as described as long as the Westpac App is ALSO installed in the main/owner profile.   However, uninstalling the Westpac App (and Google Play) from the main profile resulted in the Westpac App, in the Work profile, to immediately crash on startup.  On reinstalling the Westpac App into the main profile (even if it is Disabled) the App within the Work profile appears to work flawlessly.

The crashing described in the previous paragraph smells like a bug with Android - I recall seeing mention of a bug that prevents using a payment app with NFC in the work profile if there is no payment app installed in the main profile.     This smells similar to me!

I have not tested functionality in the app related to payment via Google Pay or NFC (as I use neither).

**Comment by fryorcraken** [comment]
agreed westpac app works with listed permissions.
