### ISSUE TITLE
CREDITAS Banking

### ISSUE THREAD

**Issue by lukashoracek** [akc3n/banking#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

CREDITAS Banking

### Link to app

https://play.google.com/store/apps/details?id=cz.creditas.richee

### App version

v3.6.0

### Country of the app

Czech Republic

### Build Number

SP2A.220405.003.2022042600

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [X] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Nothing special, just a banking app. Doesn't have built-in contactless payments.

**Comment by akc3n** [comment]
@lukashoracek hey, thanks for your submission. Apologies for not reply sooner. I'll get this added this evening
