### ISSUE TITLE
U.S. Bank Mobile

### ISSUE THREAD

**Issue by gogogohub** [akc3n/banking#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

U.S. Bank Mobile: Bank and Invest

### Link to app

https://play.google.com/store/apps/details?id=com.usbank.mobilebanking&gl=US

### App version

3.30.43

### Country of the app

United States

### Build Number

SP2A.220505.002.2022051100

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

All functions of the app appear to work including Zelle without location permission requirements. It complains about not having google play services occasionally but this probably just breaks notifications the app would send you.

**Comment by akc3n** [comment]
Thank you @gogogohub, just added it.

**Comment by ymilly** [comment]
The app behaves as expected on initial install. However, on the 2nd sign in a few oddities:

1. it doesn't remember that biometric login was selected, so I have to again input the password.
2. Login is successful, but has a extended loading period. when loading completes after 1 plus minute, the app shows the dashboard but doesn't respond to any input. Phone and other apps behave normally.

Installed from Aurora.
Google play not installed
owner account.
VPN set to US (all tried VPN whitelist for the app)
Same behavior with and without app compatibility.
touch id and other banking apps working
location enabled
pixel 6a
build 2024123000

im not sure what happens between the first and second login to prevent the app from working.

brand new to graphene. Love it. Appreciate any help.
