### ISSUE TITLE
Alliant Credit Union

### ISSUE THREAD

**Issue by gogogohub** [akc3n/banking#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Alliant Mobile Banking

### Link to app

https://play.google.com/store/apps/details?id=org.alliant.mobile&gl=US

### App version

5.1.8.221380001

### Country of the app

United States

### Build Number

SP2A.220505.002.2022051100

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

All functions of the app appear to be working.

**Comment by akc3n** [comment]
Thanks @gogogohub

**Comment by gogogohub** [comment]
They must have updated something in the last two years then.

**Comment by treadful** [comment]
This works for me now on a Pixel 8. App version 6.0.2. No Google Play Services.
