### ISSUE TITLE
Bendigo Bank

### ISSUE THREAD

**Issue by upuzzled2** [akc3n/banking#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Bendigo Bankk

### Link to app

https://play.google.com/store/apps/details?id=com.bendigobank.mobile

### App version

4.9.30

### Country of the app

Australia

### Build Number

SP1A.210812.016.C1.2022053100

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [X] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

No known issue's

**Comment by akc3n** [comment]
Oh my goodness, I am SO SORRY @upuzzled2 I simply missed this! Thank you so much for adding this!!
