### ISSUE TITLE
Länsförsäkringar

### ISSUE THREAD

**Issue by lbschenkel** [akc3n/banking#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Länsförsäkringar

### Link to app

https://play.google.com/store/apps/details?id=se.lf.mobile.android

### App version

6.14.1

### Country of the app

Sweden

### Build Number

SQ3A.220605.009.B1.2022062200

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything works as far as I can tell.

**Comment by akc3n** [comment]
Thank you @lbschenkel
