### ISSUE TITLE
Nubank

### ISSUE THREAD

**Issue by lbschenkel** [akc3n/banking#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Nubank

### Link to app

https://play.google.com/store/apps/details?id=com.nu.production

### App version

7.86.2-minApi26

### Country of the app

Brazil

### Build Number

SQ3A.220605.009.B1.2022062200

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything works as far as I can see.

**Comment by akc3n** [comment]
Thanks @lbschenkel , I'll get this up on this list tonight!

**Comment by lbschenkel** [comment]
Update: the app **may** have stopped working on GrapheneOS. Thread in their forum: https://discuss.grapheneos.org/d/12707-nubank-app-issues

**Comment by lbschenkel** [comment]
> Update: the app **may** have stopped working on GrapheneOS. Thread in their forum: https://discuss.grapheneos.org/d/12707-nubank-app-issues

New update: I was able to log in again, without any change from my side. I can't say if there was a problem with my account, which they sorted out, or if the app is refusing to work on GOS by default and they whitelisted it for me since I reached support multiple times.

I guess it would be useful to hear from other users trying to set up the app for the first time.

**Comment by FabioBentoLuiz** [comment]
Phone: Pixel 8
gos Version: 23
Nubank app version: 9.15.9-minApi28
Installation: Aurora Store (anonymous)
Main profile: no

The app starts and asks for a document number, then follows the error message: "Ocorreu um erro. Nao foi possivel carregar as informacoes. Tente novamente."

After installing the sandboxed Google Play Services (Apps > Google Play services > Install) it is working fine. I didn't have to set further permissions to Google Play Services neither login with a Google Account, just installed the services.

**Comment by lbschenkel** [comment]
Thanks for the report. Interestingly, you got the error I got but I always had Play Services from the beginning. Then one day I started getting this error, and after around 2 weeks of contacting support the issue simply disappeared. I don't quite know what happened there.

**Comment by eBug** [comment]
I'm unable to install Nubank in a secondary profile, from Google Play Store.
GrapheneOS 2025081400

**Comment by vivianemontenegro94-dev** [comment]
I was having the same problem, with a locked bootloader and even developer mode not enabled, Nubank wouldn't perform facial verification and sometimes gave an "an error occurred" message (in portuguese). So I uninstalled the Play Store services and Nubank, then reinstalled Nubank through the Aurora Store without Play Store Services, and then it worked normally. I don't know how, but the Play Store Services was being the problem to me.

**Comment by Gater73** [comment]
Phone: Pixel 7 pro
Build number: 2025121701
Nubank app version: 9.38.75-minApi28
Installation: Sandboxed Playstore
Main profile: yes

Works all features minus adding cards to google wallet obviously

**Comment by lbschenkel** [comment]
I'm pleased to say that Nubank app has added NFC payments capability and it works on GrapheneOS. You can add a card, and it also supports contactless Pix (a Brazilian payment system). I've enabled both with no issues. It also supports being the default NFC provider.

I've tested in latest stable GOS, *with* Play Services installed (I do not know if the app works without it, never tested that scenario). This app does use Play Integrity in the sense that it's on the list that GOS compiles of apps that have used it, but I've received no notification whatsoever during my experiments, meaning that Play Integrity status was not even queried (and it also does not query when launching the app).
